export const CHANGE_QUERY_PARAMS = 'CHANGE_QUERY_PARAMS';

export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTO_DETAILS = 'FETCH_PHOTO_DETAILS';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';

export const AUTH = 'AUTH';

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
